sistemaDiscusiones/sistemaDiscusiones/apps/discuss/urls.py
from django.conf.urls import patterns, include, url
from .views import QuestionListView, QuestionCreateView	

urlpatterns = patterns('',
    url(r'preguntas/$', QuestionListView.as_view(), name='questions'),
    url(r'preguntar/$', QuestionCreateView.as_view(), name='create_question'),
   
)

sistemaDiscusiones/sistemaDiscusiones/apps/home/urls.py
from django.conf.urls import patterns, include, url
from .views import IndexView

urlpatterns = patterns('',
    url(r'^$' ,IndexView.as_view()),
   # url(r'^index$' ,Index2.as_view() ),
   # url(r'^index/', Index.as_view()),
   	#url(r'^$','django.contrib.auth.views.login',{'template_name':'inicio/index.html'},name='login'),
	#url(r'^cerrar/$','django.contrib.auth.views.logout_then_login',name='logout'),
)

sistemaDiscusiones/sistemaDiscusiones/apps/users/urls.py
from django.conf.urls import patterns, include, url
from .views import UserDetailView

urlpatterns = patterns('',

	url(r'usuario/(?P<slug>[-\w]+)/$', UserDetailView.as_view(), name='user_detail'),


)

sistemaDiscusiones/sistemaDiscusiones/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sistemaDiscusiones.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^' , include('sistemaDiscusiones.apps.home.urls')),
    url(r'^' , include('sistemaDiscusiones.apps.users.urls',namespace= 'users')),
    url(r'^' , include('sistemaDiscusiones.apps.discuss.urls',namespace= 'discuss')),
)

sistemaDiscusiones/sistemaDiscusiones/apps/discuss/models.py
from django.db import models
from django.template.defaultfilters import slugify
from sistemaDiscusiones.apps.users.models import User

class TimeStampModel(models.Model):

	user = models.ForeignKey(User, db_index=True, null=True, blank=True)
	description = models.TextField()
	created = models.DateTimeField(auto_now_add = True)
	modifed = models.DateTimeField(auto_now = True)

	class Meta:
		abstract = True


class Tag(models.Model):

	nombre = models.CharField(max_length = 10)

	def __unicode__(self):
		return self.nombre


class Question(TimeStampModel):

	tag = models.ManyToManyField(Tag)
	title = models.CharField(max_length=200)
	slug = models.SlugField(editable=False, unique=True)

	def __unicode__(self):
		return '%s %s' % (self.user, self.title)

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.title)

		super(Question, self).save(*args, **kwargs)	
			


class Answer(TimeStampModel):
	def __unicode__(self):
		return self.user		

sistemaDiscusiones/sistemaDiscusiones/apps/home/models.py
from django.db import models

# Create your models here.

sistemaDiscusiones/sistemaDiscusiones/apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin


class UserManager(BaseUserManager):

	def _create_user(self, username, email, password,is_staff, is_superuser,
			**extra_fields):
		if not email:
			return ValueError('el email debe ser obligatorio')
		email = self.normalize_email(email)
		user = self.model(username=username, email=email, is_active=True,is_staff=is_staff, is_superuser=is_superuser,
				**extra_fields)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_user(self, username, email, password=None, **extra_fields):
			return self._create_user(username, email, password, False, False, **extra_fields)
	
	def create_superuser(self, username, email, password, **extra_fields):
		return  self._create_user(username, email, password, True, True, **extra_fields)									
		

class User(AbstractBaseUser,PermissionsMixin):

	username	= models.CharField(max_length=50,unique=True)
	email		= models.EmailField(max_length=50,unique=True)
	first_name	= models.CharField(max_length=100)
	last_name	= models.CharField(max_length=100)
	avatar		= models.URLField()

	objects		= UserManager()

	is_active	= models.BooleanField(default=True)
	is_staff		= models.BooleanField(default=False)	

	USERNAME_FIELD	= 'username'
	REQUIRED_FIELDS	= ['email']	

	def get_short_name(self):
		return self.username

sistemaDiscusiones/sistemaDiscusiones/apps/discuss/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from .models import Question

class CreateQuestionForm(forms.ModelForm):

	title = forms.CharField(widget = forms.TextInput(attrs={
			'class' : 'class-control',
			'placeholder' : 'título'


		}))

	description = forms.CharField(widget = forms.Textarea(attrs={
			'class' : 'class-control',
			'placeholder' : 'Contenido',
			'rows' : 4


		}))	

	class Meta:
		model =  Question

sistemaDiscusiones/sistemaDiscusiones/apps/discuss/views.py
from django.shortcuts import render
from .models import Question, Tag
from braces.views import LoginRequiredMixin

from django.views.generic import ListView, CreateView
from .forms import CreateQuestionForm


class QuestionListView(ListView):
	model = Question
	context_object_name = 'questions'

	def get_context_data(self, **kwargs):
		context = super(QuestionListView, self).get_context_data(**kwargs)
		context['tags'] = Tag.objects.all()
		return context


class QuestionCreateView(LoginRequiredMixin,CreateView):

	model = Question
	form_class = CreateQuestionForm
	success_url = '/'
	login_url = '/'

	def form_valid(self, form):
		#print "valido"
		form.instance.user = self.request.user
		return super(QuestionCreateView, self).form_valid(form)

	
	def form_invalid(self, form):
		#print "invalido"
		return super(QuestionCreateView, self).form_invalid(form)

sistemaDiscusiones/sistemaDiscusiones/apps/home/views.py
from django.shortcuts import render
from django.views.generic import ListView
from sistemaDiscusiones.apps.discuss.models import Question
from sistemaDiscusiones.apps.users.models import User

class IndexView(ListView):
#	def get(self,request,*args,**kwargs):
#		return render_to_response('inicio/index.html',context_instance = RequestContext(request))
	template_name = 'home/index.html'
	queryset = Question.objects.all()[:5]

	def get_queryset(self):
		tags = [question.tag.all() for question in self.queryset]
		return zip(self.queryset, tags)

	def get_context_data(self, **kwargs):
		context	= super(IndexView, self).get_context_data(**kwargs)
		context['total_questions'] = Question.objects.count()
		context ['total_users'] = User.objects.exclude(is_superuser=True).count()
		return context

sistemaDiscusiones/sistemaDiscusiones/apps/users/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from .models import User
from sistemaDiscusiones.apps.discuss.models import Question	
# Create your views here.

class UserDetailView(DetailView):

	model = User
	slug_field = 'username'

	def get_context_data(self, **kwargs):
		context  = super(UserDetailView, self).get_context_data(**kwargs)
		questions = Question.objects.filter(user = context['object']).order_by('created')
		tags = [ question.tag.all() for question in questions ]
		context['ques_tags'] = zip(questions , tags)
		return context

sistemaDiscusiones/sistemaDiscusiones/templates/base.html
<html lang='en'>
<head>
	<meta charset="UTF-8">
	<title>{% block tittle %} {% endblock %}</title>
	{% load static from staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	
</head>
<body>
	<h1>devCode.la</h1>
	{% block content %} {% endblock %}
	{% block footer %}
		<hr>
		<p>mensaje</p>
	{% endblock %}
</body>
</html>

sistemaDiscusiones/sistemaDiscusiones/templates/discuss/question_form.html
{% extends "base.html" %}
{%  block title %}
Registrar una pregunta
{% endblock %}
{% block content %}

	<div id="header">
			<ul class="nav">
			  <li><a href="/">Inicio</a></li>
			  <li><a href="{% url 'users:user_detail' user.username %}">perfil</a></li>
			  <li><a href="/Preguntas">Preguntas</a></li>
			</ul>

	</div>

	<h1>AQUI PUEDES REALIZAR UNA  PREGUNTA</h1>

	<form class="form-horizontal" role="form" method="POST">
		{% csrf_token %}
			
		<label>Titulo: </label>
		{{form.title}}<br>
		
		<label>Contenido:</label>
		{{form.description}}<br>
		
		<label>Tag:</label>
		{{form.tag}}<br>		
		<input type="submit" value="submit">


	</form>

	

{% endblock %}

sistemaDiscusiones/sistemaDiscusiones/templates/discuss/question_list.html
{%  block title %}
inicio
{% endblock %}
{% block content %}

	<div id="header">
			<ul class="nav">
			  <li><a href="/">Inicio</a></li>
			  <li><a href="{% url 'users:user_detail' user.username %}">perfil</a></li>
			  <li><a href="/Preguntas">Preguntas</a></li>
			</ul>

	</div>

	{% for question in questions %}
		<h4>titulo de la pregunta : {{ question.title }}</h4>
		<h4>titulo de la pregunta : {{ question.user }}</h4>
		{% for tag in tags %}

		<div class="tags"></div>
		<h1>Tags</h1>	
		<input type="button">{{ tag.nombre }}
		{% endfor %}
	{% endfor %}

{% endblock %}

sistemaDiscusiones/sistemaDiscusiones/templates/home/index.html
{% extends "base.html" %}
{%  block title %}
inicio
{% endblock %}
{% block content %}
	<div id="header">
		<ul class="nav">
		  <li><a href="/">Inicio</a></li>
		  <li><a href="{% url 'users:user_detail' user.username %}">perfil</a></li>
		  <li><a href="/preguntas">Preguntas</a></li>
		  <li><a href="/preguntar">Haz una Pregunta</a></li>
		</ul>

	</div>

	<h4>Preguntas : {{total_questions}}</h4>
	<h4>Usuarios : {{total_users}}</h4>

	{% for question, tags in object_list %}
		<h4>{{ question.title }}</h4>
		<h4>{{ question.user }}</h4>

		<h2>Tags</h2>
		{% for tag in tags %}
			{{ tag.nombre }}
		{% endfor %}	


	{% endfor %}



{% endblock %}

sistemaDiscusiones/sistemaDiscusiones/templates/users/user_detail.html
{% extends "base.html" %}
{%  block title %}
inicio
{% endblock %}
{% block content %}
	<div id="header">
		<ul class="nav">
		  <li><a href="/index">Inicio</a></li>
		  <li><a href="{% url 'users:user_detail' user.id %}">perfil</a></li>
		</ul>

	</div>

	<p>{{object.username}}</p>


{% for question, tags in ques_tags %}
	<p>{{ question.title }}</p>	
	<p>publicado el {{question.modifed}}</p>

	<p class="tags">

		<span>Etiquetas:</span>

		{% for tag in tags %}
		<p>{{tag.nombre}}</p>

		{% endfor %}
	{% endfor %}	
	


	</p>

{% endblock %}